### ISSUE TITLE
Training with RNAseq data failed 

### ISSUE THREAD

**Issue by MartinPippel** [weberlab-hhu/Helixer#105]
Hey developers, 

thanks for the awesome tool. I just tried to run train the model with extrinsic data as described [here](https://github.com/weberlab-hhu/Helixer/blob/main/docs/fine_tuning.md#tuning-with-extrinsic-information). But I got the following error message at the filter step. Any hint would be highly appreciated!

```bash
python3 /projects/martin/prog/helixer_dev_pack/Helixer/filter-to-most-certain.py --write-by 6415200 --h5-to-filter helixer.h5 --predictions predictions.h5 --keep-fraction 0.2 --output-file helixer_RNAseqfiltered.h5
selecting 995 with average normalized distances below in each genic proportion ranking [0.12242798353909465, 0.1432730078563412, 0.1257306864945754, 0.09597220030162738, 0.012006686146768612]
Traceback (most recent call last):
  File "/projects/martin/prog/helixer_dev_pack/Helixer/n90_train_val_split.py", line 66, in copy_structure
    h5_out[g][ds]
    ~~~~~~~~~^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/projects/martin/prog/conda_envs/helixer/lib/python3.11/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'rnaseq_meta' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/martin/prog/helixer_dev_pack/Helixer/filter-to-most-certain.py", line 120, in <module>
    main(args)
  File "/projects/martin/prog/helixer_dev_pack/Helixer/filter-to-most-certain.py", line 102, in main
    copy_structure(h5_in, h5_out)
  File "/projects/martin/prog/helixer_dev_pack/Helixer/n90_train_val_split.py", line 69, in copy_structure
    shape = list(dat.shape)
                 ^^^^^^^^^
AttributeError: 'Group' object has no attribute 'shape'
```

Best,
Martin

**Comment by alisandra** [comment]
Hi Martin, 

Thanks for raising this. 

Could you run `h5tree -va helixer.h5` and send me the output, please?
(h5tree is from here: https://github.com/johnaparker/h5tree, and can be installed with `pip install h5tree`).

Cheers,
Ali

**Comment by MartinPippel** [comment]
Hi Ali, 

thanks for your swift reply. Here ist output:

```
helixer.h5  (2 objects, 4 attributes)
│   ├── geenuff_commit  commit not found, version: 0.3.0
│   ├── helixer_commit  commit not found, version: 0.3.2
│   ├── input_path  Stylops_ater_helixer.sqlite3
│   ├── timestamp  2023-08-07 12:10:36.330819
├── data  (12 objects)
│   ├── X  (4990, 21384, 4), float16
│   ├── err_samples  (4990,), bool
│   ├── fully_intergenic_samples  (4990,), bool
│   ├── gene_lengths  (4990, 21384), uint32
│   ├── is_annotated  (4990,), bool
│   ├── phases  (4990, 21384, 4), int8
│   ├── sample_weights  (4990, 21384), int8
│   ├── seqids  (4990,), |S50
│   ├── species  (4990,), |S25
│   ├── start_ends  (4990, 2), int64
│   ├── transitions  (4990, 21384, 6), int8
│   └── y  (4990, 21384, 4), int8
└── evaluation  (3 objects)
    ├── rnaseq_coverage  (4990, 21384, 2), int64
    ├── rnaseq_meta  (1 object)
    │   └── bam_files  (2,), |S512
    └── rnaseq_spliced_coverage  (4990, 21384, 2), int64
```

**Comment by alisandra** [comment]
OK, I updated the two scripts:
[filter-to-most-certain.py](https://raw.githubusercontent.com/weberlab-hhu/helixer_scratch/master/data_scripts/filter-to-most-certain.py) and 
[n90_train_val_split.py](https://github.com/weberlab-hhu/helixer_scratch/blob/master/data_scripts/n90_train_val_split.py) to be much more robust and among other things handle slight differences in file formats between versions >.<

Thanks again for raising this!

As the difference is only in the location of the meta data, you should be able to resume at the filtering step where the error occurred, without any worry about downstream repercussions. 

Of course the whole tuning with RNAseq remains experimental, so keep up the good work, and let us know if you encounter any further trouble! :-)

**Comment by MartinPippel** [comment]
Thanks for your help. The script finished successfully.
