### ISSUE TITLE
KeyError: 'Unable to open object (component not found)'

### ISSUE THREAD

**Issue by ply2022** [weberlab-hhu/Helixer#115]
Hi, 

I received following error message when I was running Helixer via Singularity:

Traceback (most recent call last):
  File "/usr/local/bin/Helixer.py", line 248, in <module>
    main()
  File "/usr/local/bin/Helixer.py", line 228, in main
    model.run()
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 937, in run
    self.open_data_files()
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 797, in open_data_files
    self.shape_test = self.h5_tests[0]['/data/X'].shape
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'

Can you help me with this issue? 
Thanks.

**Comment by soi** [comment]
Hello @ply2022, 

Please provide more information like the exact command you used and the goal you tried to achieve.

All the best, 
Felix

**Comment by ply2022** [comment]
Hi Felix, thanks for the prompt reply. I realized there was an issue downloading test genome. It is running as expected now. I am closing the issue.
