### ISSUE TITLE
error message = 'No space left on device"

### ISSUE THREAD

**Issue by AlonsoLongoria23** [weberlab-hhu/Helixer#139]
Hello, I'm running helixer and I encounter this error

starting to load test data into memory..
For h5 starting with species = b'':
x shape: (17374, 213840, 4)
Data loading of 17374 (total so far 17374) samples of data/X into memory took 140.20 secs
Compressed data size of data/X is at least 1.5990 GB

setting self.n_seqs to 17374, bc that is len of data/X
Traceback (most recent call last):
  File "/usr/local/bin/Helixer.py", line 248, in <module>
    main()
  File "/usr/local/bin/Helixer.py", line 228, in main
    model.run()
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 1031, in run
    self._make_predictions(model)
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 892, in _make_predictions
    pred_out[dset_name][old_len:] = pred_dset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/dataset.py", line 999, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 282, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 115, in h5py._proxy.dset_rw
OSError: [Errno 28] Can't synchronously write data (file write failed: time = Wed Aug  7 21:49:41 2024
, filename = '/tmp/tmpx_8rm915/tmp_predictions_.h5', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x797bc7e5, total write size = 992670, bytes this sub-write = 992670, bytes actually written = 18446744073709551615, offset = 0)
INFO:    Cleaning up image...

the command I used was

singularity run --nv helixer-docker_helixer_v0.3.3_cuda_11.8.0-cudnn8.sif Helixer.py --fasta-path GCA_023634145.1_fThyThy.pri.20220222_genomic.fna.gz --lineage vertebrate --gff-output-path thymallus_thymallus_complete_helixer.gff3 --subsequence-length 213840 --overlap-offset 106920 --overlap-core-length 160380

Environment 
    OS: Ubuntu
    Container: Singularity version 3.8.0
    Web tool: Not used

**Comment by felicitas215** [comment]
Hello, it looks like your ``/tmp`` directory is running out of disk space. Try using ``--temporary-dir`` to specify a different location where the temporary files created by Helixer can be stored.
