### ISSUE TITLE
Helixer official docker not finding its own python modules when running in AWS through nextflow 

### ISSUE THREAD

**Issue by MatteoSchiavinato** [weberlab-hhu/Helixer#154]
**Describe the bug**
I have successfully run Helixer locally using the pre-constructed docker container. Note that I am running it _without GPU_. When I run it on AWS using Nextflow, this happens: 

```
  Traceback (most recent call last):
    File "/home/helixer_user/Helixer/scripts/fetch_helixer_models.py", line 5, in <module>
      from helixer.core.data import prioritized_models, fetch_and_organize_models
  ModuleNotFoundError: No module named 'helixer'
```

**To Reproduce**
This is my nextflow process:

```
process HELIXER {

    input:
    tuple \
    val(alias),
    path(fasta)

    val species
    val lineage

    output:
    tuple \
    val(alias),
    path(fasta),
    path("${alias}.gff3"), emit: models

    script:
    """
    set -e 
    set -o pipefail 

    # change directory so that modules can be found properly 
    cd /home/helixer_user/Helixer

    # download models 
    /home/helixer_user/Helixer/scripts/fetch_helixer_models.py

    # add helixer path to pythonpath 
    export PYTHONPATH="/home/helixer_user/Helixer:\${PYTHONPATH}"

    # run helixer 
    /home/helixer_user/Helixer/Helixer.py \
    --compression lzf \
    --fasta-path ${fasta} \
    --gff-output-path ${alias}.gff3 \
    --lineage ${lineage} \
    --min-coding-length 60 \
    --species ${species}
    """
```

To reproduce the behavior, all that is needed is to run this process using the preconstructed container as container for the process, with no modification.

**Error**
The error I'm getting:

```
  Traceback (most recent call last):
    File "/home/helixer_user/Helixer/scripts/fetch_helixer_models.py", line 5, in <module>
      from helixer.core.data import prioritized_models, fetch_and_organize_models
  ModuleNotFoundError: No module named 'helixer'
```

Seems to come from the fact that the environment does not find the `helixer` directory from where to load the local modules `prioritized_models` and `fetch_and_organize_models`. Even if I change directory into the one where this folder is, or if I add it to the PYTHONPATH (see the nextflow process above). 

Note that _this behavior is not observed when running locally, just in AWS_. AWS + Nextflow notoriously creates some issues when something is installed in `/usr`, i.e. chances are this something won't be found when running in the cloud (not always, but frequently). 

**Environment (please complete the following information):**
The official docker from helixer 

**Suggested fix**
I am adding a suggestion to fix it. I haven't fully tested it, but it should work if everything (including _CUDA drivers_) is installed outside of /usr, preferrably in `/opt`. 

Here's the changes I've done to the docker file:

```
FROM gglyptodon/helixer-docker:helixer_v0.3.3_cuda_11.8.0-cudnn8
USER root 
WORKDIR /opt
RUN mkdir -p /opt/Helixer_inst \
    && mv /home/helixer_user/* /opt/Helixer_inst/
WORKDIR /opt/Helixer_inst/Helixer
ENV PYTHONPATH="/opt/Helixer_inst/Helixer:${PYTHONPATH}"
CMD ["bash"]
```

This goes for the python packages too. In fact, it would be important to install them outside of `/usr/local`, e.g. just `/usr`. 

I have solved at least that issue by setting this in the dockerfile: 
```
ENV PYTHONUSERBASE=/usr 
```

**Comment by felicitas215** [comment]
Hi,
thank you for reporting this issue. Can you try setting the Python path before evoking the first python script?
Like this:
```
# add helixer path to pythonpath 
export PYTHONPATH="/home/helixer_user/Helixer:\${PYTHONPATH}"

# download models 
/home/helixer_user/Helixer/scripts/fetch_helixer_models.py
```

**Comment by MatteoSchiavinato** [comment]
That was my first attempt, but wasn't successful.

**Comment by MatteoSchiavinato** [comment]
UPDATE: I've managed to reduce the docker to about 12 GB based on your new commit and some other changes. Here it is (attached). 

[Dockerfile_v2.txt](https://github.com/user-attachments/files/17703369/Dockerfile.txt)

**Comment by felicitas215** [comment]
Could you try adding `RUN pip install --upgrade pip` to your Dockerfile. There seems to be an issue with Ubuntu 22.04 not recognizing name and version and installing UNKNOWN 0.0.0 instead of for example helixer-0.3.4. (Link to the bug report: https://github.com/pypa/setuptools/issues/3269).

**Comment by felicitas215** [comment]
I'm closing this issue, because there was no activity for 1 month. Feel free to reopen the issue if necessary.
