### ISSUE TITLE
Overlapping does not work with --chunk-size 19440

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/Helixer#58]

**Comment by soi** [comment]
./DanQModel.py -v -l /mnt/data/felix/nni-experiments/7SYI4tA8/trials/ppoJD/best_model.h5 --pool-size 9 --predict-phase --val-test-batch-size 400 --eval -t /tmp/tmp.Y4LbBg7TLq/crein.h5 --overlap --overlap-offset 3240

Traceback (most recent call last):
  File "./DanQModel.py", line 165, in <module>
    model.run()
  File "/home/felix/git/Helixer/helixer/prediction/HelixerModel.py", line 752, in run
    _, _, _ = HelixerModel.run_metrics(test_generator, model, calc_H=self.calculate_uncertainty)
  File "/home/felix/git/Helixer/helixer/prediction/HelixerModel.py", line 478, in run_metrics
    metrics = metrics_calculator.calculate_metrics(model)
  File "/home/felix/git/Helixer/helixer/prediction/Metrics.py", line 260, in calculate_metrics
    cm.count_and_calculate_one_batch(y_true, y_pred, sw)
  File "/home/felix/git/Helixer/helixer/prediction/Metrics.py", line 64, in count_and_calculate_one_batch
    y_true, y_pred = ConfusionMatrix._remove_masked_bases(y_true, y_pred, sw)
  File "/home/felix/git/Helixer/helixer/prediction/Metrics.py", line 31, in _remove_masked_bases
    y_true = y_true[sw]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 65 but corresponding boolean dimension is 64

**Comment by felicitas215** [comment]
I'm closing this issue since the DanQModel is no longer in use.
