### ISSUE TITLE
using --write-by during export failing on at least some genomes

### ISSUE THREAD

**Issue by alisandra** [weberlab-hhu/Helixer#72]
Traceback (most recent call last):
  File "/home/ali/repos/github/weberlab-hhu/Helixer/export.py", line 71, in <module>
    main(args)
  File "/home/ali/repos/github/weberlab-hhu/Helixer/export.py", line 25, in main
    controller.export(chunk_size=args.chunk_size, write_by=write_by, modes=modes, compression=args.compression,
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/exporter.py", line 223, in export
    for i, (flat_data, coord, masked_bases_perc, ig_bases_perc, h5_coord) in enumerate(numerify_outputs):
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/exporter.py", line 182, in _numerify_coord
    for coord_data, h5_coord in coord_data_gen:
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/numerify.py", line 368, in numerify
    for strand_res in CoordNumerifier._numerify_super_write_chunk(f_set, bp_coord, h5_coord, coord, max_len,
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/numerify.py", line 386, in _numerify_super_write_chunk
    xb = seq_numerifier.coord_to_matrices()
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/numerify.py", line 114, in coord_to_matrices
    self._zero_matrix()
  File "/home/ali/repos/github/weberlab-hhu/Helixer/helixer/export/numerify.py", line 92, in _zero_matrix
    self.matrix = np.zeros((self.length, self.n_cols,), self.dtype)
ValueError: negative dimensions are not allowed

**Comment by alisandra** [comment]
fixed from 78313576c23eda96a1373614564cfc766978d11d
